docker restart Aidtsadb
docker restart Odoo15db
docker restart Onedb
docker restart Twodb
docker restart Threedb
docker restart Fourdb
docker restart Fivedb
docker restart Sixdb
docker restart Sevendb
docker restart Eightdb
docker restart Ninedb
docker restart Tendb
docker restart Elevendb
docker restart Twelvedb
docker restart Thirteendb
docker restart Fourteendb
docker restart Sixteendb
docker restart Seventeendb
docker restart Eighteendb
docker restart Nineteendb
docker restart Twentydb
docker restart TwentyOnedb
docker restart TwentyTwodb
docker restart TwentyThreedb
docker restart TwentyFourdb
docker restart TwentyFivedb
docker restart TwentySixdb
docker restart TwentySevendb
docker restart TwentyEightdb
docker restart TwentyNinedb
docker restart Thirtydb
