docker restart Aidtsa
docker restart Odoo15
docker restart One
docker restart Two
docker restart Three
docker restart Four
docker restart Five
docker restart Six
docker restart Seven
docker restart Eight
docker restart Nine
docker restart Ten
docker restart Eleven
docker restart Twelve
docker restart Thirteen
docker restart Fourteen
docker restart Sixteen
docker restart Seventeen
docker restart Eighteen
docker restart Nineteen
docker restart Twenty
docker restart TwentyOne
docker restart TwentyTwo
docker restart TwentyThree
docker restart TwentyFour
docker restart TwentyFive
docker restart TwentySix
docker restart TwentySeven
docker restart TwentyEight
docker restart TwentyNine
docker restart Thirty

